<a href="https://colab.research.google.com/github/MRazaRashid/SolvedMLNotebooks/blob/main/Feature_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `Task` Do feature selection as per metods taught is session 54 on SECOM dataset.

Dataset Link : https://archive.ics.uci.edu/ml/datasets/SECOM

Drive Link : https://docs.google.com/spreadsheets/d/1dFCe1zgokabsiEr6BbWmMJtiMefkrChpJWLiG_0dDkk/edit?usp=share_link

In [33]:
# Write your Code here

### `Solution`

In [34]:
import pandas as pd

df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQtBXo5cBnDsM2fmfHPm6u72KGUS5FjPHNGMxOfYjA9-CAhmnRpwkIw_rOR3sANJIToiUU__6fbBvig/pub?gid=572763137&single=true&output=csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Columns: 592 entries, Time to Pass/Fail
dtypes: float64(590), int64(1), object(1)
memory usage: 7.1+ MB


In [35]:
df.shape

(1567, 592)

In [36]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,581,582,583,584,585,586,587,588,589,Pass/Fail
count,1561.000000,1560.000000,1553.000000,1553.000000,1553.000000,1553.0,1553.000000,1558.000000,1565.000000,1565.000000,...,618.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1566.000000,1567.000000
mean,3014.452896,2495.850231,2200.547318,1396.376627,4.197013,100.0,101.112908,0.121822,1.462862,-0.000841,...,97.934373,0.500096,0.015318,0.003847,3.067826,0.021458,0.016475,0.005283,99.670066,-0.867262
std,73.621787,80.407705,29.513152,441.691640,56.355540,0.0,6.237214,0.008961,0.073897,0.015116,...,87.520966,0.003404,0.017180,0.003720,3.578033,0.012358,0.008808,0.002867,93.891919,0.498010
min,2743.240000,2158.750000,2060.660000,0.000000,0.681500,100.0,82.131100,0.000000,1.191000,-0.053400,...,0.000000,0.477800,0.006000,0.001700,1.197500,-0.016900,0.003200,0.001000,0.000000,-1.000000
25%,2966.260000,2452.247500,2181.044400,1081.875800,1.017700,100.0,97.920000,0.121100,1.411200,-0.010800,...,46.184900,0.497900,0.011600,0.003100,2.306500,0.013425,0.010600,0.003300,44.368600,-1.000000
50%,3011.490000,2499.405000,2201.066700,1285.214400,1.316800,100.0,101.512200,0.122400,1.461600,-0.001300,...,72.288900,0.500200,0.013800,0.003600,2.757650,0.020500,0.014800,0.004600,71.900500,-1.000000
75%,3056.650000,2538.822500,2218.055500,1591.223500,1.525700,100.0,104.586700,0.123800,1.516900,0.008400,...,116.539150,0.502375,0.016500,0.004100,3.295175,0.027600,0.020300,0.006400,114.749700,-1.000000
max,3356.350000,2846.440000,2315.266700,3715.041700,1114.536600,100.0,129.252200,0.128600,1.656400,0.074900,...,737.304800,0.509800,0.476600,0.104500,99.303200,0.102800,0.079900,0.028600,737.304800,1.000000


In [37]:
df.head()

,Time,0,1,2,3,4,5,6,7,8,...,581,582,583,584,585,586,587,588,589,Pass/Fail
0,2008-07-19 11:55:00,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,...,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1
1,2008-07-19 12:32:00,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,...,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1
2,2008-07-19 13:17:00,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,...,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1
3,2008-07-19 14:43:00,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,...,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1
4,2008-07-19 15:22:00,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,...,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1


# **ML Model Before any CleanUp**

In [38]:
x_fun=df.drop(['Pass/Fail',"Time"],axis=1)
y_fun=df['Pass/Fail']

In [39]:
x_fun.shape

(1567, 590)

In [40]:
x_fun.isnull().sum().sum()

np.int64(41951)

In [41]:
y_fun.value_counts()

,count
Pass/Fail,
-1,1463
1,104


In [42]:
x_fun.select_dtypes(exclude="number").columns

Index([], dtype='object')

In [43]:
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression

# X_train, X_test, y_train, y_test = train_test_split(
#     x_fun,
#     y_fun,
#     test_size=0.2,
#     random_state=42
# )

# model = LogisticRegression()

# model.fit(X_train, y_train)

### **CleanUP**

In [44]:
x=df.drop(['Pass/Fail',"Time"],axis=1)
y=df['Pass/Fail']

In [45]:
x.shape

(1567, 590)

### Removing Constant Value/Columns

In [46]:
constant_cols=x.columns[x.nunique() <= 1]
len(constant_cols)

116

In [47]:
x=x.drop(columns=constant_cols)
x.shape

(1567, 474)

### Removing DuplicateColumns

In [48]:
duplicate_columns = x.T.duplicated()
print("Number of duplicated columns:", duplicate_columns.sum())

Number of duplicated columns: 0


## Missing values
we remove the columns if they have more than 50% of null values

In [49]:
missing = x.isnull().sum()

missing[missing > 0].sort_values(ascending=False).head(20)

,0
292,1429
157,1429
158,1429
293,1429
85,1341
358,1341
492,1341
220,1341
384,1018
111,1018


In [50]:
missing_percentage=x.isnull().mean()*100
missing_percentage.sort_values(ascending=False).head()

,0
157,91.193363
292,91.193363
293,91.193363
158,91.193363
85,85.577537


In [51]:
features_to_drop = missing_percentage[missing_percentage > 50].index   #28 columns
x=x.drop(columns=features_to_drop)
x.shape

(1567, 446)

In [52]:
x.isnull().sum().sum()

np.int64(10868)

In [53]:
(x.isnull().sum() > 0).sum()

np.int64(394)

In [54]:
print("Total missing values:", x.isnull().sum().sum())
print("Features with missing values:", (x.isnull().sum() > 0).sum())

Total missing values: 10868
Features with missing values: 394


Data Split

In [55]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [56]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

x_train = imputer.fit_transform(x_train)
x_test = imputer.transform(x_test)

In [57]:
import numpy as np

print(np.isnan(x_train).sum())
print(np.isnan(x_test).sum())

0
0


In [58]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_model.fit(x_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000, random_state=42)

In [59]:
y_pred = log_model.predict(x_test)

In [60]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[290   3]
 [ 21   0]]


In [61]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.93      0.99      0.96       293
           1       0.00      0.00      0.00        21

    accuracy                           0.92       314
   macro avg       0.47      0.49      0.48       314
weighted avg       0.87      0.92      0.90       314



###**NOW FeatureSelection on Training dataset to avoid leakage**

ANOVA / F-test

In [62]:
from sklearn.feature_selection import SelectKBest, f_classif

In [63]:
selector = SelectKBest(score_func=f_classif, k=40)

x_train_selected = selector.fit_transform(x_train, y_train)
x_test_selected = selector.transform(x_test)

In [64]:
print(x_train_selected.shape)
print(x_test_selected.shape)

(1253, 40)
(314, 40)


In [68]:
log_model_fs = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_model_fs.fit(x_train_selected, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000, random_state=42)

In [69]:
y_pred_fs = log_model_fs.predict(x_test_selected)

In [70]:
from sklearn.metrics import confusion_matrix

cm_fs = confusion_matrix(y_test, y_pred_fs)
print(cm_fs)

[[293   0]
 [ 21   0]]


In [71]:
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy = balanced_accuracy_score(y_test, y_pred_fs)

ber = 1 - balanced_accuracy

print("Balanced Accuracy:", balanced_accuracy)
print("BER:", ber)

Balanced Accuracy: 0.5
BER: 0.5


**T-Test**

In [73]:
from scipy.stats import ttest_ind
import numpy as np
x_pass = x_train[y_train == -1]
x_fail = x_train[y_train == 1]
t_scores = []

for i in range(x_train.shape[1]):
    t_stat, p_value = ttest_ind(
        x_pass[:, i],
        x_fail[:, i],
        equal_var=False
    )
    t_scores.append(abs(t_stat))

t_scores = np.array(t_scores)

top_40_indices = np.argsort(t_scores)[-40:]
x_train_ttest = x_train[:, top_40_indices]
x_test_ttest = x_test[:, top_40_indices]
print(x_train_ttest.shape)
print(x_test_ttest.shape)

(1253, 40)
(314, 40)


In [74]:
log_model_ttest = LogisticRegression(
    max_iter=1000,
    random_state=42
)

log_model_ttest.fit(x_train_ttest, y_train)
y_pred_ttest = log_model_ttest.predict(x_test_ttest)
cm_ttest = confusion_matrix(y_test, y_pred_ttest)
print(cm_ttest)

[[292   1]
 [ 21   0]]


/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [75]:
balanced_accuracy_ttest = balanced_accuracy_score(y_test, y_pred_ttest)

ber_ttest = 1 - balanced_accuracy_ttest

print("Balanced Accuracy:", balanced_accuracy_ttest)
print("BER:", ber_ttest)

Balanced Accuracy: 0.49829351535836175
BER: 0.5017064846416383


Quasi Constant

In [77]:
from scipy.stats import mode

most_common_percentage = []

for i in range(x_train.shape[1]):
    most_common_count = mode(x_train[:, i], keepdims=True).count[0]
    percentage = most_common_count / len(x_train)
    most_common_percentage.append(percentage)
most_common_percentage = np.array(most_common_percentage)

quasi_constant_features = np.where(
    most_common_percentage >= 0.99
)[0]

print("Quasi-constant features:", len(quasi_constant_features))

Quasi-constant features: 6


In [78]:
x_train_qc = np.delete(x_train, quasi_constant_features, axis=1)
x_test_qc = np.delete(x_test, quasi_constant_features, axis=1)

In [79]:
print(x_train_qc.shape)
print(x_test_qc.shape)

(1253, 440)
(314, 440)


**CoRelation**

In [81]:
import pandas as pd

x_train_df = pd.DataFrame(x_train_qc)
corr_matrix = x_train_df.corr().abs()

In [82]:
high_corr = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

high_corr_pairs = high_corr.stack()

high_corr_pairs = high_corr_pairs[
    high_corr_pairs > 0.90
]

print(high_corr_pairs)

4    126    0.999961
     217    0.999962
     310    0.905650
14   133    0.977557
     136    0.983058
              ...   
429  431    0.920938
433  434    0.995637
     435    0.999908
434  435    0.996102
437  438    0.972767
Length: 355, dtype: float64


In [83]:
print("Number of highly correlated pairs:", len(high_corr_pairs))

Number of highly correlated pairs: 355


In [84]:
correlated_pairs = high_corr_pairs.reset_index()
correlated_pairs.columns = ["Feature_1", "Feature_2", "Correlation"]

print(correlated_pairs.head(20))

    Feature_1  Feature_2  Correlation
0           4        126     0.999961
1           4        217     0.999962
2           4        310     0.905650
3          14        133     0.977557
4          14        136     0.983058
5          14        224     0.978303
6          14        227     0.983126
7          14        316     0.905653
8          14        317     0.971721
9          14        320     0.945407
10         14        322     0.913711
11         23         25     0.981509
12         32         34     1.000000
13         43         46     0.903098
14         48         49     0.924721
15         61         64     0.910233
16         62        177     0.902164
17         62        178     0.904040
18         62        268     0.946602
19         62        269     0.931128


In [85]:
unique_correlated_features = set(
    correlated_pairs["Feature_1"]
).union(
    set(correlated_pairs["Feature_2"])
)

print("Unique correlated features:", len(unique_correlated_features))

Unique correlated features: 300


**S2N**

In [86]:
import numpy as np

x_pass = x_train_qc[y_train == -1]
x_fail = x_train_qc[y_train == 1]

mean_pass = np.mean(x_pass, axis=0)
mean_fail = np.mean(x_fail, axis=0)

std_pass = np.std(x_pass, axis=0)
std_fail = np.std(x_fail, axis=0)

s2n_scores = (
    np.abs(mean_pass - mean_fail)
    / (std_pass + std_fail)
)
top_40_s2n = np.argsort(s2n_scores)[-40:]
x_train_s2n = x_train_qc[:, top_40_s2n]
x_test_s2n = x_test_qc[:, top_40_s2n]
print(x_train_s2n.shape)
print(x_test_s2n.shape)

(1253, 40)
(314, 40)


In [87]:
log_model_s2n = LogisticRegression(max_iter=1000, random_state=42)

log_model_s2n.fit(x_train_s2n, y_train)

y_pred_s2n = log_model_s2n.predict(x_test_s2n)
cm_s2n = confusion_matrix(y_test, y_pred_s2n)

print(cm_s2n)

[[292   1]
 [ 21   0]]


/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [88]:
balanced_accuracy_s2n = balanced_accuracy_score(y_test, y_pred_s2n)
ber_s2n = 1 - balanced_accuracy_s2n

print("S2N Balanced Accuracy:", balanced_accuracy_s2n)
print("S2N BER:", ber_s2n)

S2N Balanced Accuracy: 0.49829351535836175
S2N BER: 0.5017064846416383
